stages:
  - build
  - publish

build:
  image: docker:latest
  stage: build
  only:
    - master
  tags:
    - docker-builder
  script:
    - docker build --pull -t ${REGISTRY}/ciag/python:3.7  .
    - docker push ${REGISTRY}/ciag/python:3.7

publish:
  image: docker:latest
  stage: publish
  only:
    - master
  tags:
    - docker-builder
  script:
    - docker tag ${REGISTRY}/ciag/python:3.7 ciag/python3.7
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker push ciag/python3.7
